### ISSUE TITLE
Wdrożenie Akki

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#10]
Jako iż mamy już zarys przetwarzania NLP i modelowania tematów LDA (pozostał tylko ostatni etap przetwarzania, który jest niejako neizależny od pozostałych), to możan zacząć wdrażać to wszystko w aktorach Akki...

**Comment by sgalazka** [comment]
mam prostą implementację aktorów akki, tylko na razie musimy ustalić zakres ich obowiązków

**Comment by dawid-woj** [comment]
najprostsza hierachia z możliwych:
1) zestaw aktorów nadrzędnych pobiera zapytania dla różncyh zakresóœ deviceID
2) i przekazują te dane do workerów do przetowrzenia NLP + wordnet i tworzą dokumenty, które zapisują do mongoDB
