### ISSUE TITLE
Przetestowanie działania systemu dla różnych konfiguracji

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#11]
Zobaczyć (i udokumentować) jak ten nasz cały system (glównie model LDA) dla różnych parametrów/konifguracji działania:
Dla zbioru danych trenujących: reprezentatywnej części naszego zbioru danych / wszystkich danych:
* zobaczyć jak sobie radzi nasz system **dla różnych parametrów alfa i beta modelu LDA**
* zobaczyć jak sobie radzi nasz system **dla różnej liczby tematów do zamodelowania**
* zobaczyć jak sobie radzi nasz system **dla różnej liczby iteracji algorytmu LDA**
* zobaczyć jak sobie radzi nasz system **dla przypadku, gdy będziemy brać pod uwagę również słowa ze zbioru 'pozostałe' dokumentów LDA**
* zobaczyć jak sobie radzi nasz system na podzbiorze danych 'A' majac model LDA wytrenowany na innym (rozłącznym) podzbiorze danych 'B' (to wymaga dodania do kodu TopicModel siegania do topicInferencera...) ???

**Comment by sgalazka** [comment]
+można by jeszcze zrobić konfigurację w mavenie, przykładowo w TST będzie mniejsza baza z wybranymi przez nas danymi testowymi, a w PROD cała baza AOL. To nie ejst konieczne

**Comment by dawid-woj** [comment]
ja mavena się nie tykam, ale prototypem takiej diagnostyki i ogarnięcia jak to działa mogę wziąć wstępnie na siebie

**Comment by dawid-woj** [comment]
Dla zamodelowania 200 tematów w 500 iteracjach po pobieżnej analizie wyników uczenia modelu LDA wyszło, że optymalne wartości parametrów modelu wynoszą:
* alfa: 0.05 lub 0.1
* beta: 0.01 (w zasadzie tutaj jest większa dowolność, można brać coś z zakresu <0.002; 1.0>)

Co do liczby iteracji, to wystarczą wartości z zakresu <50; 500>
