### ISSUE TITLE
Projekt i implementacja ostatniego etapu przetwarzania

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#12]
Najważniejsze: jak za pomocą wytrenowanego modelu LDA, bazy dokumentów LDA i dywergencji JS optymalnie (przede wszystkim pamięciowo, wszystkich dokumentów LDA będzie ponad 230k) określić powiązania między dokumentami i jak je ze sobą grupować?

* wyciąganie rozkładu prawdopodobieństw tematów wyszukiwania i jego przypisanie do określonego dokumentu LDA
* wydajne odczytywanie dokumentów i ich powiązań z bazy
* obliczanie dywergencji JS dla każdej pary dokumentów (!!!)
* zapis powiązań między parami dokumentów do bazy
* grupowanie powiązanych par dokumentów
* zapis grup powiązanych dokumentów do bazy
* ewaluacja: obliczanie FP, TP, FN, TN i na ich podstawie metryk: precicion, recall, ew. accuracy porównując obliczone grupy z rzeczywistą bazą

**Comment by sgalazka** [comment]
Mam taką propozycję: zamieńmy double na float - będziemy mieli 2 razy mniej.
Dalsze poprawki trzeba rozważyć po zapuszczeniu algorytmu na jakimś zbiorze testowym, żebyśmy mogli okreslić ile procent par ma wystarczające powiązania.

**Comment by sgalazka** [comment]
Ewaluacja gotowa
