### ISSUE TITLE
Problem złożoności pamięciowej dywergencji JS

### ISSUE THREAD

**Issue by sgalazka** [Lukier1/-SAG-WEDT-CrossDevice#13]
Problemem może być składowanie tych dywergencji.
W JS nie ma znaczenia kolejność urządzeń w parze (JS{1,2]=JS{2,1}).
Dla 230'000 urządzeń jest 230000!/(2*229998!)=**2,65 * 10^10** par.
Każda odległość to double 8B + 2x int 4B = **16B**
Wynik **424'000'000'000B**

Propozycje:
1. Trzymać tylko dywergencje które nie przekraczają jakiegoś progu. - stwarza zagrożenie:
_jeśli będziemy dołączać urządzenia do grupy ze względu na to dane urządzenie ma wystarczającą zbliżoną dywergencję do jakiegokolwiek urządzenia z tej grupy, to może się okazać że jakaś para urządzeń z tej grupy będzie miała ze sobą niewiele wspólnego_
2. Trzymać wartość N miejsc po przecinku.

**Comment by Lukier1** [comment]
Rozwiązne naszym algorytmem.
