### ISSUE TITLE
NLP processing - przepuszczane są jednoliterowe słowa oraz frazy "www" i "http"

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#16]
jak w temacie

**Comment by dawid-woj** [comment]
w "eavaluating_lda" dodałem do stopwords.txt słowa "www", "ww" i "http", więc pozostaje tylko sprawa z jednoliterowymi słowami...

**Comment by sgalazka** [comment]
poszedł commit, jest to załatwione na etapie tokenizacji
