### ISSUE TITLE
Putting data to database

### ISSUE THREAD

**Issue by sgalazka** [Lukier1/-SAG-WEDT-CrossDevice#3]
Normalize data, convert to csv format (with commas, double quotes)

**Comment by sgalazka** [comment]
Dodaję tutka do tworzenia bazy danych
[tutorial do baz danych.txt](https://github.com/Lukier1/-SAG-WEDT-CrossDevice/files/557907/tutorial.do.baz.danych.txt)

**Comment by Lukier1** [comment]
Szczerze mowiac zamiast tutoriala do tworzenia bazy danych, wolałbym żebyś wrzucił statystyki które Ci wyliczyło. I najwyżej dumpa z bazy danych, by sobie móc na szybkości u siebie uruchomić.

**Comment by dawid-woj** [comment]
Co do statystyk to się zgadzam z Łukim, ale sama baza zajmuje 2,6 GB, więc upload na repo trochę by trwał. Propozycję statystyk jakie mogą nam się przydać spisałem w wiki jakby co...
