### ISSUE TITLE
Error: Program nawiązuje dwa połączenia z bazą mongodb

### ISSUE THREAD

**Issue by sgalazka** [Lukier1/-SAG-WEDT-CrossDevice#5]
Nie wiadomo dlaczego program nawiązuje dwa połączenia.
Logi:

> gru 27, 2016 3:03:51 PM com.mongodb.diagnostics.logging.JULLogger log
> INFO: Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
> gru 27, 2016 3:03:52 PM com.mongodb.diagnostics.logging.JULLogger log
> INFO: Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:27017
> gru 27, 2016 3:03:52 PM com.mongodb.diagnostics.logging.JULLogger log
> INFO: Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 1]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=4422221}
> gru 27, 2016 3:03:52 PM com.mongodb.diagnostics.logging.JULLogger log
> INFO: Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:27017

**Comment by dawid-woj** [comment]
to jest pełny log?

**Comment by dawid-woj** [comment]
zdaje się, że to nie jest nic strasznego:
http://stackoverflow.com/questions/38012314/why-2-connections-open-when-calling-mongoclient-instance-in-mongodb
