### ISSUE TITLE
Mechanizm logowania do stdout/pliku

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#8]
* wypadałoby mieć jakiś prosty "konifgurowalny" mechanizm logowania do pliku / stdout tego co się z naszym systemem dzieje (zwłaszcza już w kontekście jego działania na Akce, żeby wiedzieć co się dzieje)
* Stanford i Mallet też jakieś rzeczy aktualnie wyrzucają do stdout gdy działają ich modele -> wypadałoby ogarnąć jak to wyłączyć, bo czasami to przeszkadza
* ten mechanizm może być podstawą dla naszego terminalowego UI, żeby pokazywać status pracy systemu co dany okres czasu

**Comment by sgalazka** [comment]
one chyba się opierają na slf4j, może da radę je skonfigurować jednym plikiem

**Comment by dawid-woj** [comment]
no to ktoś musi to sprawdzić i ogarnąć...

**Comment by dawid-woj** [comment]
Mongo do terminala też jakieś logi wyrzuca - to tez trzeba ogarnąć

**Comment by dawid-woj** [comment]
ostatni mój commit w nlp_processing ma w sobie mechanizm logowania...
