### ISSUE TITLE
Refaktoryzacja kodu i przenosiny na mastera

### ISSUE THREAD

**Issue by dawid-woj** [Lukier1/-SAG-WEDT-CrossDevice#9]
Aktualny kod jest brzydki i quasi-scalowy:
* wypadałoby ustalić jakiś **dobry prosty schemat katalogów** w naszym repo / kodzie źródłowym -> ustalić gdzie trzymane są dane (stopwords.txt, wordnet, kolekcje mongo), jak podzielić na pakiety nasz kod, etc.
* **uspójnić nazewnictwo** klas, utilsów, etc.
* **zadbać o lepszą jakość kodu**: wykorzystać lepiej Scalę + uzognidć co do zastosowania kolekcji javowych a scalowych
* tak uporządkowany i w jakimś stopniu działający kod przenieść na **mastera**

**Comment by sgalazka** [comment]
myślę że priorytet niski, jak będziemy coś mieć albo projekt będzie dobrze szedł to można się tym zająć
